/* Interactive neighborhood viewer for PR/SR/OR spatial responsibility.
   Reads RESPONSIBILITY_DATA (from data.js, generated by export_data.py). */

(function () {
  'use strict';

  const DATA = RESPONSIBILITY_DATA;
  const NODES = DATA.nodes;
  const NODE_BY_ID = new Map(NODES.map((n) => [n.id, n]));
  const EDGES = DATA.edges; // {SR: [...], OR: [...]}
  const REMOVAL_ORDER = DATA.removal_order; // {SR: {random, localized, targeted}, OR: {...}}

  const SVG_NS = 'http://www.w3.org/2000/svg';
  const VIEW = 1000;
  const PAD = 40;

  const svg = document.getElementById('map');
  const layers = {
    parcels: document.getElementById('layer-parcels'),
    ds: document.getElementById('layer-ds'),
    regions: document.getElementById('layer-regions'),
    srLinks: document.getElementById('layer-sr-links'),
    orLinks: document.getElementById('layer-or-links'),
    buildings: document.getElementById('layer-buildings'),
    networkNodes: document.getElementById('layer-network-nodes'),
    highlight: document.getElementById('layer-highlight-links'),
    labels: document.getElementById('layer-labels'),
  };
  const tooltip = document.getElementById('tooltip');
  const legendEl = document.getElementById('legend');

  // ------------------------------------------------------------------
  // Coordinate transform: meters (EPSG:3857) -> SVG viewBox pixels
  // ------------------------------------------------------------------
  function allCoords() {
    const pts = [];
    for (const n of NODES) {
      pts.push(n.centroid);
      for (const ring of [...n.building, ...n.parcel, ...n.ds]) {
        for (const p of ring) pts.push(p);
      }
    }
    return pts;
  }

  function nodeRadius(prValue, prMin, prMax) {
    const t = prMax > prMin ? (prValue - prMin) / (prMax - prMin) : 0;
    return 6 + Math.sqrt(Math.max(0, t)) * 12; // 6..18 px, area ~ proportional to PR
  }

  const bounds = (function () {
    const pts = allCoords();
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const [x, y] of pts) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
    return { minX, minY, maxX, maxY };
  })();

  const spanX = bounds.maxX - bounds.minX;
  const spanY = bounds.maxY - bounds.minY;
  const scale = Math.min((VIEW - 2 * PAD) / spanX, (VIEW - 2 * PAD) / spanY);
  const offsetX = PAD + ((VIEW - 2 * PAD) - spanX * scale) / 2;
  const offsetY = PAD + ((VIEW - 2 * PAD) - spanY * scale) / 2;

  function proj([x, y]) {
    const px = offsetX + (x - bounds.minX) * scale;
    const py = offsetY + (bounds.maxY - y) * scale; // flip Y: geographic north (max y) -> screen top
    return [px, py];
  }

  function ringToPath(ring) {
    return ring.map(proj).map((p, i) => (i === 0 ? 'M' : 'L') + p[0].toFixed(2) + ',' + p[1].toFixed(2)).join(' ') + ' Z';
  }

  function ringsToPath(rings) {
    return rings.map(ringToPath).join(' ');
  }

  function el(tag, attrs) {
    const e = document.createElementNS(SVG_NS, tag);
    for (const k in attrs) e.setAttribute(k, attrs[k]);
    return e;
  }

  function fmt(v) {
    if (v >= 1e6) return (v / 1e6).toFixed(2) + 'M';
    if (v >= 1e3) return (v / 1e3).toFixed(1) + 'K';
    return v.toFixed(0);
  }

  function lerpColor(c1, c2, t) {
    const a = hexToRgb(c1), b = hexToRgb(c2);
    const r = Math.round(a[0] + (b[0] - a[0]) * t);
    const g = Math.round(a[1] + (b[1] - a[1]) * t);
    const bl = Math.round(a[2] + (b[2] - a[2]) * t);
    return `rgb(${r},${g},${bl})`;
  }
  function hexToRgb(hex) {
    const v = parseInt(hex.slice(1), 16);
    return [(v >> 16) & 255, (v >> 8) & 255, v & 255];
  }

  const METRIC_COLORS = {
    PR: ['#eafaf0', '#1b5e3a'],
    SR: ['#fdece0', '#8a2f07'],
    OR: ['#e5f0fb', '#1a4971'],
  };
  const METRIC_UNIT = { resp: 'ft³/min', area: 'ft²' };
  const REGION_KEY = { PR: 'pr_region', SR: 'sr_region', OR: 'or_region' };
  // Links get a wider, darker-topped ramp than the region fills so the
  // highest-weight edges are clearly distinguishable from the lowest, not
  // just "reddish" vs "reddish".
  const LINK_COLORS = { SR: ['#f6c9ce', '#7a0f22'], OR: ['#bcd8f2', '#0c2c4d'] };

  // ------------------------------------------------------------------
  // Base GIS layers
  // ------------------------------------------------------------------
  function renderParcels() {
    for (const n of NODES) {
      if (!n.parcel.length) continue;
      layers.parcels.appendChild(el('path', { d: ringsToPath(n.parcel), class: 'parcel-shape' }));
    }
  }

  function renderDS() {
    for (const n of NODES) {
      if (!n.ds.length) continue;
      layers.ds.appendChild(el('path', { d: ringsToPath(n.ds), class: 'ds-shape' }));
    }
  }

  const buildingPathById = new Map();

  function renderBuildings() {
    for (const n of NODES) {
      if (!n.building.length) continue;
      const path = el('path', { d: ringsToPath(n.building), class: 'building-shape', 'data-id': n.id });
      path.addEventListener('click', () => onBuildingClick(n.id));
      path.addEventListener('mousemove', (ev) => showTooltip(ev, n));
      path.addEventListener('mouseleave', hideTooltip);
      layers.buildings.appendChild(path);
      buildingPathById.set(n.id, path);
    }
  }

  const networkNodeById = new Map();

  // Shared PR range so node-circle radius (and edge perimeter trimming,
  // which uses the same radius as a stand-in for "the node's visual edge"
  // in both Map and Network view) is computed identically everywhere.
  const PR_MIN = 0;
  const PR_MAX = Math.max(...NODES.map((n) => n.PR_resp)) || 1;

  function renderNetworkNodes() {
    const [c1, c2] = METRIC_COLORS.PR;
    for (const n of NODES) {
      const [cx, cy] = proj(n.centroid);
      const t = Math.min(1, (n.PR_resp - PR_MIN) / (PR_MAX - PR_MIN));
      const r = nodeRadius(n.PR_resp, PR_MIN, PR_MAX);
      const circle = el('circle', {
        cx: cx.toFixed(2), cy: cy.toFixed(2), r: r.toFixed(2),
        fill: lerpColor(c1, c2, t),
        class: 'network-node',
        'data-id': n.id,
      });
      circle.addEventListener('click', () => onBuildingClick(n.id));
      circle.addEventListener('mousemove', (ev) => showTooltip(ev, n));
      circle.addEventListener('mouseleave', hideTooltip);
      layers.networkNodes.appendChild(circle);
      networkNodeById.set(n.id, circle);
    }
  }

  // House-number annotations, drawn in the topmost layer so they're always
  // legible over regions/buildings/nodes/links regardless of view mode.
  function renderLabels() {
    for (const n of NODES) {
      const [cx, cy] = proj(n.centroid);
      layers.labels.appendChild(el('text', {
        x: cx.toFixed(2), y: cy.toFixed(2),
        class: 'house-label', 'data-id': n.id,
        'text-anchor': 'middle', 'dominant-baseline': 'central',
      })).textContent = n.id;
    }
  }

  function showTooltip(ev, n) {
    tooltip.classList.remove('hidden');
    tooltip.style.left = ev.offsetX + 14 + 'px';
    tooltip.style.top = ev.offsetY + 10 + 'px';
    tooltip.innerHTML = `<b>House ${n.id}</b><br>PR ${fmt(n.PR_resp)} ft&sup3;/min<br>SR ${fmt(n.SR_resp)} ft&sup3;/min<br>OR ${fmt(n.OR_resp)} ft&sup3;/min`;
  }
  function hideTooltip() { tooltip.classList.add('hidden'); }

  // ------------------------------------------------------------------
  // Links (SR / OR), directed with arrowheads, colored by weight so
  // individual edge magnitudes are distinguishable, not just network type.
  // ------------------------------------------------------------------
  const linkElsByNetwork = { SR: [], OR: [] };
  const CURVE_AMOUNT = 11; // px offset of the arc's midpoint, perpendicular to the straight line

  function edgeKey(e) { return e.source + '->' + e.target; }

  // Quadratic-bezier arc from (x1,y1) to (x2,y2), bowed to one side, plus
  // the point/tangent at the arc's midpoint (used to place the arrowhead
  // there instead of at the endpoint). Because the perpendicular offset
  // direction is derived from (x2-x1, y2-y1), a reciprocal pair of directed
  // edges (A->B and B->A) automatically bow to OPPOSITE sides of the
  // straight line between them -- the direction vector flips sign, so the
  // perpendicular does too. That's what keeps two overlapping in/out edges
  // between the same two houses visually distinct instead of perfectly
  // overlapping. (For a quadratic bezier, the tangent at t=0.5 always
  // equals the straight P2-P0 direction, so the arrow angle is just
  // atan2(y2-y1, x2-x1) -- no calculus needed at render time.)
  function computeCurve(x1, y1, x2, y2, amount) {
    const mx = (x1 + x2) / 2;
    const my = (y1 + y2) / 2;
    const dx = x2 - x1;
    const dy = y2 - y1;
    const len = Math.sqrt(dx * dx + dy * dy) || 1;
    const px = -dy / len;
    const py = dx / len;
    const cx = mx + px * amount;
    const cy = my + py * amount;
    // Bezier point at t=0.5: 0.25*P0 + 0.5*P1 + 0.25*P2
    const midX = 0.25 * x1 + 0.5 * cx + 0.25 * x2;
    const midY = 0.25 * y1 + 0.5 * cy + 0.25 * y2;
    const angleDeg = Math.atan2(dy, dx) * (180 / Math.PI);
    return {
      d: `M ${x1.toFixed(2)},${y1.toFixed(2)} Q ${cx.toFixed(2)},${cy.toFixed(2)} ${x2.toFixed(2)},${y2.toFixed(2)}`,
      midX, midY, angleDeg,
    };
  }

  // Endpoint trimmed from `fromNode`'s centroid toward `toNode`'s centroid
  // by fromNode's visual radius, so the line starts/ends at the node's
  // perimeter rather than disappearing under its center.
  function trimToward(fromNode, toNode) {
    const [fx, fy] = proj(fromNode.centroid);
    const [tx, ty] = proj(toNode.centroid);
    const dx = tx - fx, dy = ty - fy;
    const len = Math.sqrt(dx * dx + dy * dy) || 1;
    const r = nodeRadius(fromNode.PR_resp, PR_MIN, PR_MAX);
    return [fx + (dx / len) * r, fy + (dy / len) * r];
  }

  function arrowTriangle(midX, midY, angleDeg, color) {
    return el('path', {
      d: 'M -5,-3.4 L 5,0 L -5,3.4 Z',
      transform: `translate(${midX.toFixed(2)},${midY.toFixed(2)}) rotate(${angleDeg.toFixed(2)})`,
      fill: color,
      class: 'link-arrowhead',
    });
  }

  function renderLinks(network, group, cls) {
    const list = EDGES[network];
    const maxWeight = Math.max(...list.map((e) => e.weight)) || 1;
    const [c1, c2] = LINK_COLORS[network];
    for (const e of list) {
      const sourceNode = NODE_BY_ID.get(e.source);
      const targetNode = NODE_BY_ID.get(e.target);
      const [x1, y1] = trimToward(sourceNode, targetNode);
      const [x2, y2] = trimToward(targetNode, sourceNode);
      const wt = Math.min(1, e.weight / maxWeight);
      const color = lerpColor(c1, c2, wt);
      const { d, midX, midY, angleDeg } = computeCurve(x1, y1, x2, y2, CURVE_AMOUNT);
      const line = el('path', {
        d, class: 'link-line ' + cls, fill: 'none', stroke: color,
        'stroke-width': (1.1 + wt * 2.6).toFixed(2),
        'data-source': e.source, 'data-target': e.target, 'data-weight': e.weight,
      });
      const arrow = arrowTriangle(midX, midY, angleDeg, color);
      arrow.classList.add(cls, 'link-arrow-for');
      group.appendChild(line);
      group.appendChild(arrow);
      linkElsByNetwork[network].push({ el: line, arrow, edge: e });
    }
  }

  // ------------------------------------------------------------------
  // Choropleth (PR / SR / OR region shapes) -- multiple layers can be on
  // at once since the three regions are geometrically disjoint subsets of
  // each node's defensible space, so their fills never overlap or hide
  // each other.
  // ------------------------------------------------------------------
  const choropleth = { mode: 'resp', layers: { PR: true, SR: true, OR: true } };

  function renderChoropleth() {
    layers.regions.innerHTML = '';
    const activeLayers = ['PR', 'SR', 'OR'].filter((k) => choropleth.layers[k]);
    const legendBlocks = [];

    for (const layerKey of activeLayers) {
      const metric = `${layerKey}_${choropleth.mode}`;
      const values = NODES.map((n) => n[metric]);
      const max = Math.max(...values) || 1;
      const [c1, c2] = METRIC_COLORS[layerKey];
      const regionKey = REGION_KEY[layerKey];

      for (const n of NODES) {
        const rings = n[regionKey];
        if (!rings || !rings.length) continue;
        const t = Math.min(1, n[metric] / max);
        layers.regions.appendChild(el('path', {
          d: ringsToPath(rings),
          class: 'region-shape',
          fill: lerpColor(c1, c2, t),
          'fill-opacity': 0.85,
        }));
      }

      legendBlocks.push(`
        <div class="legend-block">
          <div class="legend-title">${layerKey} &mdash; ${choropleth.mode === 'resp' ? 'Responsibility' : 'Area'} [${METRIC_UNIT[choropleth.mode]}]</div>
          <div class="legend-bar" style="background:linear-gradient(90deg, ${c1}, ${c2})"></div>
          <div class="legend-range"><span>0</span><span>${fmt(max)}</span></div>
        </div>
      `);
    }
    legendEl.innerHTML = legendBlocks.join('');
  }

  // ------------------------------------------------------------------
  // Selection + connection highlighting (top-left popup on the map)
  // ------------------------------------------------------------------
  let selectedId = null;
  const popup = document.getElementById('selection-popup');

  function onBuildingClick(id) {
    if (selectedId === id) { clearSelection(); return; }
    selectedId = id;
    renderSelection();
  }

  function clearSelection() {
    selectedId = null;
    renderSelection();
  }

  function renderSelection() {
    for (const [, path] of buildingPathById) path.classList.remove('selected', 'neighbor');
    for (const [, circle] of networkNodeById) circle.classList.remove('selected', 'neighbor');
    layers.highlight.innerHTML = '';

    if (selectedId === null) {
      popup.classList.add('hidden');
      return;
    }
    popup.classList.remove('hidden');

    const n = NODE_BY_ID.get(selectedId);
    buildingPathById.get(selectedId).classList.add('selected');
    if (networkNodeById.get(selectedId)) networkNodeById.get(selectedId).classList.add('selected');

    document.getElementById('sel-id').textContent = selectedId;
    document.getElementById('sel-pr-area').textContent = fmt(n.PR_area);
    document.getElementById('sel-pr-resp').textContent = fmt(n.PR_resp);
    document.getElementById('sel-sr-area').textContent = fmt(n.SR_area);
    document.getElementById('sel-sr-resp').textContent = fmt(n.SR_resp);
    document.getElementById('sel-or-area').textContent = fmt(n.OR_area);
    document.getElementById('sel-or-resp').textContent = fmt(n.OR_resp);

    const srIncident = EDGES.SR.filter((e) => e.source === selectedId || e.target === selectedId);
    const srIn = EDGES.SR.filter((e) => e.target === selectedId).length;
    const srOut = EDGES.SR.filter((e) => e.source === selectedId).length;
    document.getElementById('sel-sr-in').textContent = srIn;
    document.getElementById('sel-sr-out').textContent = srOut;

    // OR direction: edge (source -> target) means target owes source.
    // "owed to sel" = sel is source (others owe sel); "owed by sel" = sel is target (sel owes others).
    const orOwedTo = EDGES.OR.filter((e) => e.source === selectedId).length;
    const orOwedBy = EDGES.OR.filter((e) => e.target === selectedId).length;
    document.getElementById('sel-or-in').textContent = orOwedTo;
    document.getElementById('sel-or-out').textContent = orOwedBy;

    const orIncident = EDGES.OR.filter((e) => e.source === selectedId || e.target === selectedId);
    const neighborIds = new Set();
    for (const e of [...srIncident, ...orIncident]) {
      neighborIds.add(e.source === selectedId ? e.target : e.source);
    }
    for (const nid of neighborIds) {
      const p = buildingPathById.get(nid);
      if (p) p.classList.add('neighbor');
      const c = networkNodeById.get(nid);
      if (c) c.classList.add('neighbor');
    }

    for (const e of srIncident) drawHighlightLink(e);
    for (const e of orIncident) drawHighlightLink(e);
  }

  function drawHighlightLink(e) {
    const sourceNode = NODE_BY_ID.get(e.source);
    const targetNode = NODE_BY_ID.get(e.target);
    const [x1, y1] = trimToward(sourceNode, targetNode);
    const [x2, y2] = trimToward(targetNode, sourceNode);
    const { d, midX, midY, angleDeg } = computeCurve(x1, y1, x2, y2, CURVE_AMOUNT);
    layers.highlight.appendChild(el('path', { d, class: 'link-highlight', fill: 'none' }));
    layers.highlight.appendChild(arrowTriangle(midX, midY, angleDeg, '#ff3b30'));
  }

  // ------------------------------------------------------------------
  // Active network (SR or OR) -- single source of truth for both which
  // links are drawn on the map and which network the simulation below
  // operates on, so the two views can never disagree.
  // ------------------------------------------------------------------
  let activeNetwork = 'SR';

  function setActiveNetwork(network) {
    activeNetwork = network;
    document.querySelectorAll('.network-pill').forEach((b) => b.classList.toggle('active', b.dataset.network === network));
    layers.srLinks.style.display = network === 'SR' ? '' : 'none';
    layers.orLinks.style.display = network === 'OR' ? '' : 'none';
    document.getElementById('sim-network-label').textContent = network;
    sim.network = network;
    updateSimulation();
  }

  // ------------------------------------------------------------------
  // Mitigation simulation (random / localized / targeted link removal)
  // ------------------------------------------------------------------
  const sim = { network: 'SR', strategy: 'targeted', fraction: 0, playing: false, rafId: null };

  function totalWeight(network) {
    return EDGES[network].reduce((s, e) => s + e.weight, 0);
  }

  function updateSimulation() {
    const order = REMOVAL_ORDER[sim.network][sim.strategy];
    const total = order.length;
    const numRemoved = Math.round(sim.fraction * total);
    const removedSet = new Set(order.slice(0, numRemoved).map((e) => e.source + '->' + e.target));

    for (const network of ['SR', 'OR']) {
      const isSimNetwork = network === sim.network;
      for (const { el: lineEl, arrow, edge } of linkElsByNetwork[network]) {
        const removed = isSimNetwork && removedSet.has(edgeKey(edge));
        lineEl.classList.toggle('removed', removed);
        arrow.classList.toggle('removed', removed);
      }
    }

    const remainingEdges = EDGES[sim.network].filter((e) => !removedSet.has(edgeKey(e)));
    const remainingWeight = remainingEdges.reduce((s, e) => s + e.weight, 0);
    const pct = total === 0 ? 100 : (remainingWeight / totalWeight(sim.network)) * 100;

    document.getElementById('sim-links-removed').textContent = numRemoved;
    document.getElementById('sim-links-total').textContent = total;
    document.getElementById('sim-remaining-pct').textContent = pct.toFixed(1) + '%';
    document.getElementById('sim-active-subnets').textContent = countActiveSubnetworks(remainingEdges);
    document.getElementById('sim-slider-label').textContent = Math.round(sim.fraction * 100) + '%';
  }

  function countActiveSubnetworks(edges) {
    const adj = new Map();
    for (const e of edges) {
      if (!adj.has(e.source)) adj.set(e.source, new Set());
      if (!adj.has(e.target)) adj.set(e.target, new Set());
      adj.get(e.source).add(e.target);
      adj.get(e.target).add(e.source);
    }
    const visited = new Set();
    let count = 0;
    for (const start of adj.keys()) {
      if (visited.has(start)) continue;
      count++;
      const stack = [start];
      visited.add(start);
      while (stack.length) {
        const cur = stack.pop();
        for (const nb of adj.get(cur)) {
          if (!visited.has(nb)) { visited.add(nb); stack.push(nb); }
        }
      }
    }
    return count;
  }

  function setSimStrategy(strategy) {
    sim.strategy = strategy;
    document.querySelectorAll('.pill[data-strategy]').forEach((b) => b.classList.toggle('active', b.dataset.strategy === strategy));
    updateSimulation();
  }

  function playSimulation() {
    const btn = document.getElementById('sim-play');
    if (sim.playing) {
      sim.playing = false;
      btn.innerHTML = '&#9654; Play';
      if (sim.rafId) cancelAnimationFrame(sim.rafId);
      return;
    }
    sim.playing = true;
    btn.innerHTML = '&#10074;&#10074; Pause';
    if (sim.fraction >= 1) sim.fraction = 0;
    const durationMs = 6000;
    const startFraction = sim.fraction;
    const startTime = performance.now();
    const slider = document.getElementById('sim-slider');

    function step(now) {
      if (!sim.playing) return;
      const elapsed = now - startTime;
      const t = Math.min(1, elapsed / (durationMs * (1 - startFraction)));
      sim.fraction = startFraction + t * (1 - startFraction);
      slider.value = Math.round(sim.fraction * 100);
      updateSimulation();
      if (sim.fraction < 1) {
        sim.rafId = requestAnimationFrame(step);
      } else {
        sim.playing = false;
        btn.innerHTML = '&#9654; Play';
      }
    }
    sim.rafId = requestAnimationFrame(step);
  }

  function resetSimulation() {
    sim.playing = false;
    sim.fraction = 0;
    if (sim.rafId) cancelAnimationFrame(sim.rafId);
    document.getElementById('sim-slider').value = 0;
    document.getElementById('sim-play').innerHTML = '&#9654; Play';
    updateSimulation();
  }

  // ------------------------------------------------------------------
  // Wire up UI
  // ------------------------------------------------------------------
  let viewMode = 'map';

  function applyGisLayerVisibility() {
    if (viewMode !== 'map') return;
    layers.parcels.style.display = document.getElementById('toggle-parcels').checked ? '' : 'none';
    layers.buildings.style.display = document.getElementById('toggle-buildings').checked ? '' : 'none';
    layers.ds.style.display = document.getElementById('toggle-ds').checked ? '' : 'none';
  }

  function initLayerToggles() {
    document.getElementById('toggle-parcels').addEventListener('change', applyGisLayerVisibility);
    document.getElementById('toggle-buildings').addEventListener('change', applyGisLayerVisibility);
    document.getElementById('toggle-ds').addEventListener('change', applyGisLayerVisibility);
    document.getElementById('toggle-labels').addEventListener('change', (e) => {
      layers.labels.style.display = e.target.checked ? '' : 'none';
    });
  }

  function setViewMode(mode) {
    viewMode = mode;
    svg.classList.toggle('mode-network', mode === 'network');
    svg.classList.toggle('mode-map', mode === 'map');
    document.querySelectorAll('.view-pill').forEach((b) => b.classList.toggle('active', b.dataset.view === mode));

    if (mode === 'network') {
      layers.parcels.style.display = 'none';
      layers.buildings.style.display = 'none';
      layers.ds.style.display = 'none';
      layers.regions.style.display = 'none';
      layers.networkNodes.style.display = '';
    } else {
      layers.networkNodes.style.display = 'none';
      layers.regions.style.display = '';
      applyGisLayerVisibility();
    }
  }

  function initViewModePills() {
    document.querySelectorAll('.view-pill').forEach((b) => {
      b.addEventListener('click', () => setViewMode(b.dataset.view));
    });
  }

  function initNetworkPills() {
    document.querySelectorAll('.network-pill').forEach((b) => {
      b.addEventListener('click', () => setActiveNetwork(b.dataset.network));
    });
  }

  function initChoroplethControls() {
    document.querySelectorAll('.mode-pill').forEach((b) => {
      b.addEventListener('click', () => {
        document.querySelectorAll('.mode-pill').forEach((x) => x.classList.remove('active'));
        b.classList.add('active');
        choropleth.mode = b.dataset.mode;
        renderChoropleth();
      });
    });
    document.querySelectorAll('.layer-toggle').forEach((cb) => {
      cb.addEventListener('change', () => {
        choropleth.layers[cb.dataset.layer] = cb.checked;
        renderChoropleth();
      });
    });
  }

  function initSimControls() {
    document.querySelectorAll('.pill[data-strategy]').forEach((b) => {
      b.addEventListener('click', () => setSimStrategy(b.dataset.strategy));
    });
    document.getElementById('sim-slider').addEventListener('input', (e) => {
      sim.playing = false;
      document.getElementById('sim-play').innerHTML = '&#9654; Play';
      if (sim.rafId) cancelAnimationFrame(sim.rafId);
      sim.fraction = Number(e.target.value) / 100;
      updateSimulation();
    });
    document.getElementById('sim-play').addEventListener('click', playSimulation);
    document.getElementById('sim-reset').addEventListener('click', resetSimulation);
    document.getElementById('clear-selection').addEventListener('click', clearSelection);
    document.getElementById('clear-selection-btn').addEventListener('click', clearSelection);

    setSimStrategy('targeted');
  }

  function initAboutModal() {
    const modal = document.getElementById('about-modal');
    document.getElementById('about-btn').addEventListener('click', () => modal.classList.remove('hidden'));
    document.getElementById('about-close').addEventListener('click', () => modal.classList.add('hidden'));
    modal.addEventListener('click', (e) => { if (e.target === modal) modal.classList.add('hidden'); });
  }

  // ------------------------------------------------------------------
  // Zoom / pan. A single transform on #viewport (translate then scale) --
  // every rendering function above still draws into the fixed 0..1000
  // coordinate space, so none of that code needed to change.
  // ------------------------------------------------------------------
  const viewportEl = document.getElementById('viewport');
  const zoom = { scale: 1, tx: 0, ty: 0 };
  const ZOOM_MIN = 0.5;
  const ZOOM_MAX = 10;

  function applyZoomTransform() {
    viewportEl.setAttribute('transform', `translate(${zoom.tx.toFixed(2)},${zoom.ty.toFixed(2)}) scale(${zoom.scale.toFixed(4)})`);
  }

  // Client (mouse/touch) coords -> fixed 0..1000 viewBox coords, independent
  // of the current zoom/pan (i.e. "where in the untransformed map is this").
  function clientToViewBox(clientX, clientY) {
    const rect = svg.getBoundingClientRect();
    const vbX = ((clientX - rect.left) / rect.width) * VIEW;
    const vbY = ((clientY - rect.top) / rect.height) * VIEW;
    return [vbX, vbY];
  }

  // Zoom by `factor` while keeping the point under (vbX, vbY) fixed on
  // screen -- the standard "zoom toward cursor/pinch center" behavior.
  function zoomAt(vbX, vbY, factor) {
    const newScale = Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, zoom.scale * factor));
    const actualFactor = newScale / zoom.scale;
    zoom.tx = vbX - (vbX - zoom.tx) * actualFactor;
    zoom.ty = vbY - (vbY - zoom.ty) * actualFactor;
    zoom.scale = newScale;
    applyZoomTransform();
  }

  function resetZoom() {
    zoom.scale = 1; zoom.tx = 0; zoom.ty = 0;
    applyZoomTransform();
  }

  function initZoomPan() {
    svg.addEventListener('wheel', (e) => {
      e.preventDefault();
      const [vbX, vbY] = clientToViewBox(e.clientX, e.clientY);
      const factor = e.deltaY < 0 ? 1.15 : 1 / 1.15;
      zoomAt(vbX, vbY, factor);
    }, { passive: false });

    // Mouse drag to pan. Attached to the SVG itself; individual building/
    // node click handlers are unaffected since a plain click (no movement
    // between mousedown/mouseup) still fires the browser's native click
    // event on that element regardless of these listeners.
    let dragging = false;
    let lastX = 0, lastY = 0;

    svg.addEventListener('mousedown', (e) => {
      dragging = true;
      lastX = e.clientX; lastY = e.clientY;
      svg.classList.add('panning');
    });
    window.addEventListener('mousemove', (e) => {
      if (!dragging) return;
      const rect = svg.getBoundingClientRect();
      zoom.tx += (e.clientX - lastX) * (VIEW / rect.width);
      zoom.ty += (e.clientY - lastY) * (VIEW / rect.height);
      lastX = e.clientX; lastY = e.clientY;
      applyZoomTransform();
    });
    window.addEventListener('mouseup', () => {
      dragging = false;
      svg.classList.remove('panning');
    });

    // Touch: one finger pans, two fingers pinch-zoom.
    let touchMode = null; // 'pan' | 'pinch'
    let pinchStartDist = 0;
    let pinchStartScale = 1;
    let panLastX = 0, panLastY = 0;

    function touchDist(t0, t1) {
      return Math.hypot(t1.clientX - t0.clientX, t1.clientY - t0.clientY);
    }
    function touchMid(t0, t1) {
      return [(t0.clientX + t1.clientX) / 2, (t0.clientY + t1.clientY) / 2];
    }

    svg.addEventListener('touchstart', (e) => {
      if (e.touches.length === 1) {
        touchMode = 'pan';
        panLastX = e.touches[0].clientX;
        panLastY = e.touches[0].clientY;
      } else if (e.touches.length === 2) {
        touchMode = 'pinch';
        pinchStartDist = touchDist(e.touches[0], e.touches[1]);
        pinchStartScale = zoom.scale;
      }
    }, { passive: true });

    svg.addEventListener('touchmove', (e) => {
      e.preventDefault();
      if (touchMode === 'pan' && e.touches.length === 1) {
        const rect = svg.getBoundingClientRect();
        const t = e.touches[0];
        zoom.tx += (t.clientX - panLastX) * (VIEW / rect.width);
        zoom.ty += (t.clientY - panLastY) * (VIEW / rect.height);
        panLastX = t.clientX; panLastY = t.clientY;
        applyZoomTransform();
      } else if (touchMode === 'pinch' && e.touches.length === 2) {
        const dist = touchDist(e.touches[0], e.touches[1]);
        const [midX, midY] = touchMid(e.touches[0], e.touches[1]);
        const [vbX, vbY] = clientToViewBox(midX, midY);
        const targetScale = Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, pinchStartScale * (dist / pinchStartDist)));
        zoomAt(vbX, vbY, targetScale / zoom.scale);
      }
    }, { passive: false });

    svg.addEventListener('touchend', (e) => {
      if (e.touches.length === 0) touchMode = null;
      else if (e.touches.length === 1) {
        touchMode = 'pan';
        panLastX = e.touches[0].clientX;
        panLastY = e.touches[0].clientY;
      }
    });

    document.getElementById('zoom-in').addEventListener('click', () => zoomAt(VIEW / 2, VIEW / 2, 1.3));
    document.getElementById('zoom-out').addEventListener('click', () => zoomAt(VIEW / 2, VIEW / 2, 1 / 1.3));
    document.getElementById('zoom-reset').addEventListener('click', resetZoom);
  }

  function init() {
    renderParcels();
    renderDS();
    renderLinks('SR', layers.srLinks, 'sr');
    renderLinks('OR', layers.orLinks, 'or');
    renderBuildings();
    renderNetworkNodes();
    renderLabels();
    renderChoropleth();
    initLayerToggles();
    initChoroplethControls();
    initViewModePills();
    initNetworkPills();
    initSimControls();
    initAboutModal();
    initZoomPan();
    setViewMode('map');
    setActiveNetwork('SR');
    renderSelection();
  }

  init();
})();
